"""rename address

Revision ID: 774d9471cfa1
Revises: becff5467771
Create Date: 2025-06-12 18:30:49.446827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774d9471cfa1'
down_revision = 'becff5467771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
