"""rename department

Revision ID: becff5467771
Revises: 6708494a4e1f
Create Date: 2025-06-12 18:27:42.675727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becff5467771'
down_revision = '6708494a4e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
